server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: yun-picture
  datasource:
    url: jdbc:mysql://localhost:3306/yun_picture
    username: root
    password: 2026535085
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0 # 表示未删除
      logic-delete-value: 1 # 表示已删除

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.example.yunpicturebackend.controller

